# Generated by Django 2.2.10 on 2021-08-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_choice_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='survey',
        ),
    ]
