# Generated by Django 2.2.10 on 2021-08-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20210806_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text input'), ('select', 'choose one'), ('select-multiple', 'choose any')], default='text', max_length=200),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
