# Generated by Django 2.2.10 on 2021-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_respondent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='name',
        ),
        migrations.AddField(
            model_name='respondent',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
