# Generated by Django 2.2.10 on 2021-08-09 08:34

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_auto_20210809_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='active',
            field=computed_property.fields.ComputedBooleanField(compute_from='is_active', default=True, editable=False),
            preserve_default=False,
        ),
    ]
