# Generated by Django 2.2.10 on 2021-08-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_survey_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='active',
        ),
    ]
